import 'package:learningapp/main/utils/AppConstant.dart';

const learner_walk_BackImg = "images/learnerimage/learnerWalkBackImg.png";
const learner_walk_1 = "images/learnerimage/learner_walk_1.png";
const learner_walk_2 = "$BaseUrl/images/learnerimage/learner_walk_2.png";
const learner_walk_3 = "$BaseUrl/images/learnerimage/learner_walk_3.png";

const learner_ic_bag = "images/learnerimage/learner_ic_bag.png";
const learner_ic_alfatihah = "images/ic_alfatihah.png";
const learner_ic_300 = "assets/payment.png";
const learner_ic_comingsoon = "images/ic_comingsoon.png";
const learner_ic_cake = "images/learnerimage/t9_ic_cake.png";
const learner_ic_crown = "images/learnerimage/learner_ic_crown.png";
const learner_ic_cup = "images/learnerimage/learner_ic_cup.png";
const learner_ic_flag = "images/learnerimage/learner_ic_flag.png";
const learner_ic_medal = "images/learnerimage/learner_ic_medal.png";
const learner_ic_pencil_scale = "images/learnerimage/learner_ic_pencil_scale.png";
const learner_ic_crome = "images/learnerimage/learner_ic_crome.png";
const learner_ic_telecope = "images/learnerimage/learner_ic_telecope.png";
const learner_ic_Cake = "$BaseUrl/images/learnerimage/learner_ic_cake.png";
const learner_green_image = "$BaseUrl/images/learnerimage/learner_green_image.png";
const learner_climb = "$BaseUrl/images/learnerimage/learner_climb.png";
const learner_ic_heart = "images/learnerimage/learner_ic_heart.svg";
const learner_ic_user = "images/learnerimage/learner_ic_user.svg";
const learner_ic_achievements = "images/learnerimage/learner_ic_achievements.svg";
const learner_ic_key = "images/learnerimage/learner_ic_key.svg";
const learner_ic_logout = "images/learnerimage/learner_ic_logout.svg";
const learner_ic_correct = "images/learnerimage/learner_ic_correct.svg";
const learner_ic_block = "images/learnerimage/learner_ic_block.svg";
const learner_ic_check = "images/learnerimage/learner_ic_check.png";
const learner_ic_uncheck = "images/learnerimage/learner_ic_uncheck.png";

const learner_ic_Profile = "images/ic_profile.png";
const learner_ic_profile1 = "$BaseUrl/images/learnerimage/learner_ic_profile1.jpg";
const learner_ic_profile2 = "$BaseUrl/images/learnerimage/learner_ic_profile2.jpeg";
const learner_ic_profile3 = "$BaseUrl/images/learnerimage/learner_ic_profile3.jpeg";
const learner_ic_profile4 = "$BaseUrl/images/learnerimage/learner_ic_profile4.jpeg";
const learner_ic_profile5 = "$BaseUrl/images/learnerimage/learner_ic_profile5.jpeg";
const learner_ic_profile6 = "$BaseUrl/images/learnerimage/learner_ic_profile6.jpeg";
const learner_ic_profile7 = "$BaseUrl/images/learnerimage/learner_ic_profile7.jpeg";
const learner_ic_Img = "$BaseUrl/images/learnerimage/learner_ic_Img1.png";
const learner_ic_fab_back = "images/learnerimage/learner_ic_fab_back.png";
const learner_ic_smile = "images/learnerimage/learner_ic_smile.png";
const learner_ic_upload = "images/learnerimage/learner_ic_upload.png";

const Learner_ic_chart_navigation = "images/learnerimage/learner_ic_chart_navigation.svg";
const Learner_ic_home_navigation = "images/learnerimage/learner_ic_home_navigation.svg";
const Learner_ic_message_navigation = "images/learnerimage/learner_ic_message_navigation.svg";
const Learner_ic_more_navigation = "images/learnerimage/learner_ic_more_navigation.svg";
const Learner_ic_search_navigation = "images/learnerimage/learner_ic_search_navigation.svg";
